In [12]:
import os
import pandas as pd
import numpy as np

In [30]:
shark_data = pd.read_csv("attacks.csv")

In [14]:
shark_data.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson�McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [15]:
shark_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

In [22]:
shark_data.drop('Name', axis=1)
cshark_data = shark_data.drop(['Name', 'original order', 'Investigator or Source', 'pdf', 'href formula', 'Case Number.1','Case Number.2', 'Unnamed: 22', 'Unnamed: 23'], axis=1)

In [23]:
shark_columns = list(cshark_data.columns)
shark_clean_col = [col.lower().strip().replace(' ','_') for col in shark_columns]

In [24]:
cshark_data.columns = shark_clean_col
cshark_data.head(50)

,case_number,date,year,type,country,area,location,activity,sex,age,injury,fatal_(y/n),time,species,href
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,M,NaN,"No injury, board bitten",N,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,18,FATAL,Y,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'",http://sharkattackfile.net/spreadsheets/pdf_di...
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,M,15,Lower left leg bitten,N,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,M,12,Minor injury to foot,N,14h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
11,2018.05.21,21-May-2018,2018.0,Unprovoked,USA,South Carolina,"Isle of Palms, Charleston County",Boogie boarding,M,10,Injuries to lower right leg and foot,N,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
12,2018.05.13.b,13-May-2018,2018.0,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,M,10,Severe bite to right forearm,N,15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,F,34,Shallow lacerations to finger PROVOKED INCIDENT,N,NaN,"Tawny nurse shark, 2m",http://sharkattackfile.net/spreadsheets/pdf_di...
15,2018.05.12,12-May-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,"Nahoon Beach, East London",Surfing,M,NaN,"Minor injury, marks on board",N,11h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
16,2018.05.09,09-May-2018,2018.0,Questionable,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,M,NaN,"No injury, surfboard damaged",N,10h30,Shark involvement not confirmed,http://sharkattackfile.net/spreadsheets/pdf_di...
17,2018.04.30.R,Reported 30-Apr-2018,2018.0,Unprovoked,THAILAND,Hua Hin,Sai Noi Beach,Swimming,M,NaN,Minor injury to ankle,N,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
18,2018.04.28.b,28-Apr-2018,2018.0,Unprovoked,COSTA RICA,Cocos Island,Manuelita,Scuba diving,M,30,"No injury, shark bit scuba gear",N,10h40,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
19,2018.04.28.a,28-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Gearys Beach,Surfing,M,NaN,"No injury, knocked off board by shark",N,16h50,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
20,2018.04.25.b,25-Apr-2018,2018.0,Questionable,AUSTRALIA,New South Wales,Lennox Head,Surfing,M,NaN,No injury,N,07h00,Questionable,http://sharkattackfile.net/spreadsheets/pdf_di...
21,2018.04.25.a,25-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,M,60,"No injury, knocked off board by shark",N,09h30,3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
22,2018.04.24,24-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"South Point, Gracetown",Surfing,M,NaN,"No injury, shark struck his leg",N,Afternoon,"White shark, 3.5 m",http://sharkattackfile.net/spreadsheets/pdf_di...
23,2018.04.23,23-Apr-2018,2018.0,Unprovoked,MALDIVES,Alifu Alifu Atoll,Madoogali,Fishing,M,32,5-inch cut to hand,N,21h50,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
24,2018.04.22,22-Apr-2018,2018.0,Unprovoked,SOUTH AFRICA,Western Cape Province,"Robberg Beach, Plettenberg Bay",Paddle-skiing,M,33,"No injury, shark bit hole in ski",N,09h40,"White shark, 2.5 m",http://sharkattackfile.net/spreadsheets/pdf_di...
25,2018.04.19,19-Apr-2018,2018.0,Unprovoked,USA,Hawaii,"Shipwreck�s Beach, Keoneloa Bay, Kauai",Body boarding,M,29,Lacerations to right lower leg,N,NaN,6' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
26,2018.04.15.d,15-Apr-2018,2018.0,Unprovoked,THAILAND,Hua Hin,Sai Noi Beach,Swimming,M,54,Lacerations to foot and ankle,N,NaN,Juvenile bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
28,2018.04.15.b,15-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Lefthanders, Margaret River Area",Surfing,M,41,Laceration to right thigh,N,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
29,2018.04.15.a,15-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Cobblestones, Margaret River Area",Surfing,M,37,Lacerations to legs,N,08h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
30,2018.04.14,14-Apr-2018,2018.0,Unprovoked,BAHAMAS,New Providence,Nirvana Beach,Surfing,M,NaN,No Injury. Shark swam away with the surf board,N,09h30,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
31,2018.04.10.R,Reported 10-Apr-2018,2018.0,Invalid,BRAZIL,Alagoas,"Praia de Saua�uhy, Macei�",Fishing,M,56,Injury to ankle from marine animal trapped in ...,N,NaN,Shark involvement not confirmed,http://sharkattackfile.net/spreadsheets/pdf_di...
32,2018.04.09,09-Apr-2018,2018.0,Unprovoked,NEW CALEDONIA,NaN,"Magenta Beach, Noumea",Windsurfing,NaN,NaN,"No injury, shark bit board",N,17h00,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
33,2018.04.05,05-Apr-2018,2018.0,Unprovoked,BAHAMAS,NaN,Bimini,Swimming,M,12,"2 puncture wounds to left foot, abrasion to ri...",N,18h00,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...
34,2018.04.03,03-Apr-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,St. Francis Bay,Surfing,M,19,Lacerations to left knee & lower leg,N,15h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
35,2018.03.31,31-Mar-2018,2018.0,Unprovoked,USA,Hawaii,Kukio Beach,Stand-Up Paddleboarding,M,25,Injuries to right leg & hand,N,09h30,"Tiger shark, 12'",http://sharkattackfile.net/spreadsheets/pdf_di...
36,2018.03.14,14-Mar-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Waterman's Bay,Wading,M,10,Minor injuries to legs,N,17h35,Wobbegong shark,http://sharkattackfile.net/spreadsheets/pdf_di...
37,2018.03.09.b,9-Mar-2018,2018.0,Unprovoked,AUSTRALIA,Victoria,Lorne,Swimming,M,69,"No injury, said to have been charged by sharks...",N,15h30,3.5 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
38,2018.03.09.a,9-Mar-2018,2018.0,Unprovoked,AUSTRALIA,Victoria,Winkipop,Surfing,M,18,"Minor injury, ankle grazed",N,07h30,1.8 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
39,2018.02.24,24-Feb-2018,2018.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Scuba Diving,M,38,The shark & man simply collided; neither were...,N,NaN,Blacktip shark,http://sharkattackfile.net/spreadsheets/pdf_di...
40,2018.02.23,23-Feb-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Little Congwong Beach, La Perouse",Swimming,F,55,Laceratons to right leg & foot,N,"19h00, Dusk","Juvenile white shark, 2.7 to 3.2 m",http://sharkattackfile.net/spreadsheets/pdf_di...
41,2018.02.17,18-Feb-2018,2018.0,Provoked,AUSTRALIA,Victoria,Westernport Bay,Kayak fishing for sharks,M,34,"Shark rammed kayak, no injury to occupant PRO...",N,Night,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
42,2018.02.15,15-Feb-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Surf Beach, Kiama",Walking,M,35,Puncture wounds to leff foot & lower leg,N,16h00,"Bull shark, 2 m",http://sharkattackfile.net/spreadsheets/pdf_di...
43,2018.02.14,14-Feb-2018,2018.0,Invalid,AUSTRALIA,Queensland,Mooloolaba Beach,Swimming,F,NaN,"Collision / No injury, no attack",N,18h00,Possibly a wobbegong,http://sharkattackfile.net/spreadsheets/pdf_di...
44,2018.02.11,11-Feb-2018,2018.0,Invalid,BRAZIL,"Boi Island, Victoria",Espirito Santo,Cleaning fish,F,46,Lacerations to 4 toes of right foot,N,NaN,"Injury believed caused by an eel, not a shark",http://sharkattackfile.net/spreadsheets/pdf_di...
45,2018.02.03,03-Feb-2018,2018.0,Unprovoked,ECUADOR,Galapagos Islands,Santa Fe Island,Snorkeling,M,45,Injuries to right foot,N,NaN,Galapagos shark?,http://sharkattackfile.net/spreadsheets/pdf_di...
46,2018.02.01,01-Feb-2018,2018.0,Invalid,AUSTRALIA,Western Australia,"Avalon Point, Manurah",Spearfishing,M,14,"No injury no attack. This is considerd an ""enc...",N,NaN,2m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
47,2018.01.28,28-Jan-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Cone Bay,NaN,M,18,Injuries to right leg,N,08h00,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...
48,2018.01.21,21-Jan-2018,2018.0,Unprovoked,NEW CALEDONIA,NaN,Nouville,Spearfishing,M,40s,Injuries to abdomen and arm,N,15h30,"Bull shark, 3 m",http://sharkattackfile.net/spreadsheets/pdf_di...
49,2018.01.14,14-Jan-2018,2018.0,Unprovoked,AUSTRALIA,Queensland,Lizard Island,Diving,M,NaN,Severe laceration to left forearm,N,15h01,Grey reef shark. 2 m,http://sharkattackfile.net/spreadsheets/pdf_di...

In [35]:
cshark_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   case_number   8702 non-null   object
 1   date          6302 non-null   object
 2   year          6300 non-null   object
 3   type          6298 non-null   object
 4   country       6252 non-null   object
 5   area          5847 non-null   object
 6   location      5762 non-null   object
 7   activity      5758 non-null   object
 8   sex           5737 non-null   object
 9   age           3471 non-null   object
 10  injury        6274 non-null   object
 11  fatal_(y/n)   5763 non-null   object
 12  time          2948 non-null   object
 13  species       3464 non-null   object
 14  href_formula  6301 non-null   object
 15  unnamed:_22   1 non-null      object
 16  unnamed:_23   2 non-null      object
dtypes: object(17)
memory usage: 3.3+ MB

In [ ]:
#A a maior parte nos estados unidos, surfando, homens, 17 anos, perto de 2015,
#verificar injury pois não está coerente, a tarde, tubarões brancos.

In [36]:
cshark_data.describe()

,case_number,date,year,type,country,area,location,activity,sex,age,injury,fatal_(y/n),time,species,href_formula,unnamed:_22,unnamed:_23
count,8702,6302,6300.0,6298,6252,5847,5762,5758,5737,3471,6274,5763,2948,3464,6301,1,2
unique,6287,5433,249.0,8,212,825,4108,1532,6,157,3737,8,366,1549,6290,1,2
top,0,1957,2015.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,17,FATAL,N,Afternoon,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,stopped here,change filename
freq,2400,11,143.0,4595,2229,1037,163,971,5094,154,802,4293,187,163,2,1,1

In [28]:
cshark_data.tail(100)

,case_number,date,year,type,country,area,location,activity,sex,age,injury,fatal_(y/n),time,species,href
25623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25627,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
cshark_data['type'].unique()

array(['Boating', 'Unprovoked', 'Invalid', 'Provoked', 'Questionable',
       'Sea Disaster', nan, 'Boat', 'Boatomg'], dtype=object)

In [66]:
cshark_data['type'].value_counts()

Unprovoked      4595
Provoked         574
Invalid          547
Sea Disaster     239
Boating          203
Boat             137
Questionable       2
Boatomg            1
Name: type, dtype: int64

In [19]:
cshark_data['Country'].unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
       'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'NEW CALEDONIA',
       'ECUADOR', 'MALAYSIA', 'LIBYA', nan, 'CUBA', 'MAURITIUS',
       'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS', 'JAPAN',
       'EGYPT', 'ST HELENA, British overseas territory', 'COMOROS',
       'REUNION', 'FRENCH POLYNESIA', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
       'COLUMBIA', 'CAPE VERDE', 'Fiji', 'DOMINICAN REPUBLIC',
       'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE', 'FIJI', 'PUERTO RICO',
       'ITALY', 'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA',
       'RUSSIA', 'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
       'YEMEN', 'GULF OF ADEN', 'Sierra Leone', 'ST. MAARTIN',
       'GRAND CAYMAN', 'Seychelles', 'LIBERIA', 'VANUATU', 'MEXICO ',
       'HONDURAS', 'VENEZUELA', 'SRI LANKA', ' TONGA', 'URUGUAY', 'INDIA',
       'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA',
       'MARSHALL ISLANDS', 'EGYPT / ISRAEL', 'NORTHERN ARABIAN SEA',
       'HONG KONG', 'EL SALVADOR', 'ANGOLA', 'BERMUDA', 'MONTENEGRO',
       'IRAN', 'TUNISIA', 'NAMIBIA', 'NORTH ATLANTIC OCEAN', 'PORTUGAL',
       'SOUTH CHINA SEA', 'BANGLADESH', 'PALAU', 'WESTERN SAMOA',
       'PACIFIC OCEAN ', 'BRITISH ISLES', 'GRENADA', 'IRAQ', 'TURKEY',
       'SINGAPORE', 'NEW BRITAIN', 'SUDAN', 'JOHNSTON ISLAND',
       'SOUTH PACIFIC OCEAN', 'NEW GUINEA', 'RED SEA',
       'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
       'MID ATLANTIC OCEAN', 'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'RED SEA / INDIAN OCEAN',
       'PACIFIC OCEAN', 'NORTH SEA', 'NICARAGUA ', 'MALDIVE ISLANDS',
       'AMERICAN SAMOA', 'ANDAMAN / NICOBAR ISLANDAS', 'GABON', 'MAYOTTE',
       'NORTH ATLANTIC OCEAN ', 'THE BALKANS', 'SUDAN?', 'ARGENTINA',
       'MARTINIQUE', 'INDIAN OCEAN', 'GUATEMALA', 'NETHERLANDS ANTILLES',
       'NORTHERN MARIANA ISLANDS', 'IRAN / IRAQ', 'JAVA', 'SIERRA LEONE',
       ' PHILIPPINES', 'NICARAGUA', 'CENTRAL PACIFIC',
       'SOLOMON ISLANDS / VANUATU', 'SOUTHWEST PACIFIC OCEAN',
       'BAY OF BENGAL', 'MID-PACIFC OCEAN', 'SLOVENIA', 'CURACAO',
       'ICELAND', 'ITALY / CROATIA', 'BARBADOS', 'MONACO', 'GUYANA',
       'HAITI', 'SAN DOMINGO', 'IRELAND', 'KUWAIT', 'YEMEN ',
       'REUNION ISLAND', 'FALKLAND ISLANDS', 'CRETE', 'CYPRUS', 'EGYPT ',
       'WEST INDIES', 'BURMA', 'LEBANON', 'PARAGUAY',
       'BRITISH NEW GUINEA', 'CEYLON', 'OCEAN', 'GEORGIA', 'SYRIA',
       'TUVALU', 'INDIAN OCEAN?', 'GUINEA', 'ANDAMAN ISLANDS',
       'EQUATORIAL GUINEA / CAMEROON', 'COOK ISLANDS', 'TOBAGO', 'PERU',
       'AFRICA', 'ALGERIA', 'Coast of AFRICA', 'TASMAN SEA', 'GHANA',
       'GREENLAND', 'MEDITERRANEAN SEA', 'SWEDEN', 'ROATAN',
       'Between PORTUGAL & INDIA', 'DJIBOUTI', 'BAHREIN', 'KOREA',
       'RED SEA?', 'ASIA?', 'CEYLON (SRI LANKA)'], dtype=object)

In [56]:
cshark_data['country'].value_counts()

USA                          2229
AUSTRALIA                    1338
SOUTH AFRICA                  579
PAPUA NEW GUINEA              134
NEW ZEALAND                   128
                             ...
RED SEA                         1
GHANA                           1
ANDAMAN ISLANDS                 1
SOLOMON ISLANDS / VANUATU       1
REUNION ISLAND                  1
Name: country, Length: 212, dtype: int64

In [57]:
cshark_data['age'].unique()

array(['57', '11', '48', nan, '18', '52', '15', '12', '32', '10', '21',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '19', '25',
       '69', '38', '55', '35', '46', '45', '14', '40s', '28', '20', '24',
       '26', '49', '22', '7', '31', '17', '40', '13', '42', '3', '8',
       '50', '16', '82', '73', '20s', '68', '51', '39', '58', 'Teen',
       '47', '61', '65', '36', '66', '43', '60s', '9', '72', '59', '6',
       '27', '64', '23', '71', '44', '62', '63', '70', '18 months', '53',
       '30s', '50s', 'teen', '77', '74', '28 & 26', '5', '86', '18 or 20',
       '12 or 13', '46 & 34', '28, 23 & 30', 'Teens', '36 & 26',
       '8 or 10', '84', '� ', ' ', '30 or 36', '6�', '21 & ?', '75',
       '33 or 37', 'mid-30s', '23 & 20', ' 30', '7      &    31', ' 28',
       '20?', "60's", '32 & 30', '16 to 18', '87', '67', 'Elderly',
       'mid-20s', 'Ca. 33', '74 ', '45 ', '21 or 26', '20 ', '>50',
       '18 to 22', 'adult', '9 & 12', '? & 19', '9 months', '25 to 35',
       '23 & 26', '1', '(adult)', '33 & 37', '25 or 28',
       '37, 67, 35, 27,  ? & 27', '21, 34,24 & 35', '30 & 32', '50 & 30',
       '17 & 35', 'X', '"middle-age"', '13 or 18', '34 & 19', '33 & 26',
       '2 to 3 months', 'MAKE LINE GREEN', ' 43', '81', '"young"',
       '7 or 8', '78', '17 & 16', 'F', 'Both 11', '9 or 10', 'young',
       '36 & 23', '  ', 'A.M.', '?    &   14', '10 or 12', '31 or 33',
       '2�', '13 or 14'], dtype=object)

In [58]:
cshark_data['age'].value_counts()

17         154
18         150
19         142
20         141
15         139
          ...
�            1
23 & 26      1
Elderly      1
adult        1
67           1
Name: age, Length: 157, dtype: int64

In [59]:
cshark_data['activity'].unique()

array(['Paddling', 'Standing', 'Surfing', ...,
       'Crew swimming alongside their anchored ship',
       '4 men were bathing', 'Wreck of  large double sailing canoe'],
      dtype=object)

In [60]:
cshark_data['activity'].value_counts()

Surfing                                             971
Swimming                                            869
Fishing                                             431
Spearfishing                                        333
Bathing                                             162
                                                   ...
Swimming between  anchored  pearling luggers          1
Swimming to shore from capsized sailboat              1
U-177 torpedoed & sank the troopship Nova Scotia      1
Swimming 10 m from shore                              1
Swimming after his canoe capsized                     1
Name: activity, Length: 1532, dtype: int64

In [61]:
cshark_data['species'].unique()

array(['White shark', nan, '2 m shark', ..., "12' tiger shark",
       'Blue pointers',
       'Said to involve a grey nurse shark that leapt out of the water and  seized the boy but species identification is questionable'],
      dtype=object)

In [62]:
cshark_data['species'].value_counts()

White shark                                                       163
Shark involvement prior to death was not confirmed                105
Invalid                                                           102
Shark involvement not confirmed                                    88
Tiger shark                                                        73
                                                                 ...
According to Carlsmith, the shark's mouth was 3' wide               1
Bull shark, 4 m [13']                                               1
His hand was found in a 2.4 m [8'] tiger shark caught 1/5/1949      1
Thought to involve bull sharks                                      1
3m shark                                                            1
Name: species, Length: 1549, dtype: int64

In [63]:
cshark_data['year'].unique()

array([2018.0, 2017.0, nan, 2016.0, 2015.0, 2014.0, 2013.0, 2012.0,
       2011.0, 2010.0, 2009.0, 2008.0, 2007.0, 2006.0, 2005.0, 2004.0,
       2003.0, 2002.0, 2001.0, 2000.0, 1999.0, 1998.0, 1997.0, 1996.0,
       1995.0, 1984.0, 1994.0, 1993.0, 1992.0, 1991.0, 1990.0, 1989.0,
       1969.0, 1988.0, 1987.0, 1986.0, 1985.0, 1983.0, 1982.0, 1981.0,
       1980.0, 1979.0, 1978.0, 1977.0, 1976.0, 1975.0, 1974.0, 1973.0,
       1972.0, 1971.0, 1970.0, 1968.0, 1967.0, 1966.0, 1965.0, 1964.0,
       1963.0, 1962.0, 1961.0, 1960.0, 1959.0, 1958.0, 1957.0, 1956.0,
       1955.0, 1954.0, 1953.0, 1952.0, 1951.0, 1950.0, 1949.0, 1948.0,
       1848.0, 1947.0, 1946.0, 1945.0, 1944.0, 1943.0, 1942.0, 1941.0,
       1940.0, 1939.0, 1938.0, 1937.0, 1936.0, 1935.0, 1934.0, 1933.0,
       1932.0, 1931.0, 1930.0, 1929.0, 1928.0, 1927.0, 1926.0, 1925.0,
       1924.0, 1923.0, 1922.0, 1921.0, 1920.0, 1919.0, 1918.0, 1917.0,
       1916.0, 1915.0, 1914.0, 1913.0, 1912.0, 1911.0, 1910.0, 1909.0,
       1908.0, 1907.0, 1906.0, 1905.0, 1904.0, 1903.0, 1902.0, 1901.0,
       1900.0, 1899.0, 1898.0, 1897.0, 1896.0, 1895.0, 1894.0, 1893.0,
       1892.0, 1891.0, 1890.0, 1889.0, 1888.0, 1887.0, 1886.0, 1885.0,
       1884.0, 1883.0, 1882.0, 1881.0, 1880.0, 1879.0, 1878.0, 1877.0,
       1876.0, 1875.0, 1874.0, 1873.0, 1872.0, 1871.0, 1870.0, 1869.0,
       1868.0, 1867.0, 1866.0, 1865.0, 1864.0, 1863.0, 1862.0, 1861.0,
       1860.0, 1859.0, 1858.0, 1857.0, 1856.0, 1855.0, 1853.0, 1852.0,
       1851.0, 1850.0, 1849.0, 1847.0, 1846.0, 1845.0, 1844.0, 1842.0,
       1841.0, 1840.0, 1839.0, 1837.0, 1836.0, 1835.0, 1834.0, 1832.0,
       1831.0, 1830.0, 1829.0, 1828.0, 1827.0, 1826.0, 1825.0, 1823.0,
       1822.0, 1819.0, 1818.0, 1817.0, 1816.0, 1815.0, 1812.0, 1811.0,
       1810.0, 1808.0, 1807.0, 1805.0, 1804.0, 1803.0, 1802.0, 1801.0,
       1800.0, 1797.0, 1792.0, 1791.0, 1788.0, 1787.0, 1786.0, 1785.0,
       1784.0, 1783.0, 1780.0, 1779.0, 1776.0, 1771.0, 1767.0, 1764.0,
       1758.0, 1753.0, 1751.0, 1749.0, 1755.0, 1748.0, 1742.0, 1738.0,
       1733.0, 1723.0, 1721.0, 1703.0, 1700.0, 1642.0, 1638.0, 1637.0,
       1617.0, 1595.0, 1580.0, 1555.0, 1554.0, 1543.0, 500.0, 77.0, 5.0,
       0.0], dtype=object)

In [65]:
cshark_data['year'].value_counts()

2015.0    143
2017.0    136
2016.0    130
2011.0    128
2014.0    127
         ...
1807.0      1
1805.0      1
1804.0      1
1802.0      1
1791.0      1
Name: year, Length: 249, dtype: int64

In [93]:
CS1 = cshark_data.groupby('Country')
CS1

In [40]:
cshark = cshark_data.dropna(thresh = 0.1*len(cshark_data.columns), axis=0)

In [43]:
pd.to_datetime(cshark['date'])

ParserError: Unknown string format: Reported 30-Apr-2018

In [47]:
import re

In [59]:
 re.findall('\d{2}-\D{3}-\d+', "Reported 30-Apr-2018 ")

['30-Apr-2018']

In [73]:
def change_date(name):
    date1 = re.findall('\d{2}-\D{3}-\d+', name)
    if len(date1)>0:
        return date1[0]

In [75]:
cshark['date'] = cshark['date'].apply(change_date)

<ipython-input-75-803a69df7c4a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cshark['date'] = cshark['date'].apply(change_date)

In [68]:
cshark[cshark['date'].apply(change_date)==2]

,case_number,date,year,type,country,area,location,activity,sex,age,injury,fatal_(y/n),time,species,href
4439,1951.08.00,Between 01-Aug-1951 & 08-Aug-1951,1951.0,Unprovoked,COLUMBIA,Caribbean Sea,Cartegena,Bathing,NaN,NaN,FATAL,Y,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
4682,1943.03.02.a,02-Mar-1943 to 07-Mar-1943,1943.0,Sea Disaster,PAPUA NEW GUINEA,Morobe Province,Huon Gulf,Known as The Battle of the Bismarck Sea : 8 J...,NaN,NaN,"An estimated 3,000 to 7,000 Japanese troops p...",Y,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
4705,1942.09.11,11-Sep-1942 to 16-Sep-1942,1942.0,Sea Disaster,SOUTHWEST PACIFIC OCEAN,NaN,Southwestern Pacific Base,Adrift on life raft,M,NaN,"FATAL, 2 of the 9 airmen killed by sharks",Y,NaN,Tiger shark & others,http://sharkattackfile.net/spreadsheets/pdf_di...
5116,1928.01.21.a,Some time between 08-Jan-1928 & 21-Jan-1928,1928.0,Invalid,USA,Florida,Off Florida coast,Jumped overboard and swimming,M,NaN,"FATAL, presumed taken by shark/s",NaN,Night,Shark involvement not confirmed,http://sharkattackfile.net/spreadsheets/pdf_di...
5168,1925.03.27,07-Mar-1925 or 27-Mar-1925,1925.0,Unprovoked,AUSTRALIA,New South Wales,Coogee,Bathing in waist-deep water,M,16,"Left thigh bitten, leg surgically amputated",N,17h00,Said to be a �small shark�,http://sharkattackfile.net/spreadsheets/pdf_di...
5413,1909.11.14,14-Nov-1909 to 19-Nov-1909,1909.0,Sea Disaster,INDONESIA,30 nm from Singapore,Rhio Strait,The 2379-ton French steamer La Seyne collied w...,NaN,NaN,"FATAL, 101 people perished, including commande...",Y,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...

In [55]:
cshark['date']

0       25-Jun-2018
1       18-Jun-2018
2       09-Jun-2018
3       08-Jun-2018
4       04-Jun-2018
           ...
6297    Before 1903
6298    Before 1903
6299      1900-1905
6300      1883-1889
6301      1845-1853
Name: date, Length: 6302, dtype: object